version: "3.9"
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
    #  - ./tmp/db:/var/lib/postgresql/data
      - postgresql-data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: password
    tty: true
    stdin_open: true

  web:
    build: .
    #bin/rails アクセス拒否
    #https://qiita.com/tands4247/questions/8389892fef23e2c4a3ec

    #Rails 7でTailwind CSSを使ってみた
    #https://qiita.com/345dvl/items/4bafb05964281079033e

    #command: bash -c "rm -f tmp/pids/server.pid && bundle exec bin/rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec chmod +x bin/rails && 
             bundle exec rails tailwindcss:build && bundle exec bin/rails s -p 3000 -b '0.0.0.0'"
    #command: bash -c "rm -f tmp/pids/server.pid && bundle exec chmod +x bin/dev && 
    #         bundle exec rails tailwindcss:build && bundle exec bin/dev        
                                                                      
    #command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgresql-data:
    driver: local