version: '3.9'

services:
  db:
    image: postgres:16.0
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    tty: true
    stdin_open: true

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  web:
    build:
      context: .
      dockerfile: Dockerfile.web  # ウェブアプリケーション用のDockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec chmod +x bin/rails && bundle exec rails tailwindcss:build && bundle exec bin/rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    env_file: .env
    environment:
      - KEY_DERIVATION_SALT=${KEY_DERIVATION_SALT}
    volumes:
      - .:/myapp
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis

  node:
    build:
      context: .
      dockerfile: Dockerfile.node  # Node.js用のDockerfile
    volumes:
      - .:/myapp  # 必要に応じてボリュームをマウント
    # その他の設定...

volumes:
  postgresql-data:
    driver: local
